name: Trigger Node App Deployment

on:
  push:
    branches:
      - main

jobs:
  trigger-node:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Repo-2 Deployment
        run: |
          curl -X POST https://api.github.com/repos/itzownway/simple-node-azure/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.REPO2_PAT }}" \
          -d '{"event_type": "trigger-deploy"}'